# Site
name: "AZCastle"
title: "AZCastle"
description: "A place for my stuff on the web."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: /
#baseurl: /mediumish-theme-jekyll
#google_analytics: ''
#disqus: 'demowebsite'
#mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bruce:
    name: Bruce
    display_name: Bruce    
    avatar: 'assets/images/bruce-headshotavatar.png'
    email: bduplanty@gmail.com
    web: https://www.azcastle.com
    twitter: https://twitter.com/bduplanty
    description: "Educator, musician, ham radio operator, wanna be coder and woodworker..."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
